### ISSUE TITLE
Make release?

### ISSUE THREAD

**Issue by zamlz** [HannesMann/gcadapter-oc-kmod#1]
Hi! Thank you for this! Would you mind making an official release of this repo? I'd like to add it to my package manager.

**Comment by HannesMann** [comment]
You mean making a release here on GitHub? Sure. Considering it hasn't been updated since 2017 I just tagged the latest commit as 1.0 :). It could be worth looking into rewriting the module to support overclocking without having to unplug the adapter. It shouldn't be TOO hard to do.

**Comment by pavethem** [comment]
Regarding the need to unplug the adapter: Is there currently no way to apply this module at boot time (e.g. via modprobe) without having to plug it back in?
If there is, maybe you could add a dkms.conf for rebuilding the module automatically for every kernel update?

**Comment by HannesMann** [comment]
@pavethem If I remember correctly the problem is that the module can only find the adapter device when a device is plugged in (it uses `usb_register_notify` which is only called when a device is added or removed). This shouldn't change even at boot time, though I haven't tried it myself.

**Comment by HannesMann** [comment]
Solved the issue pretty quickly, v1.1 overclocks the adapter as soon as you load the module. DKMS seems to be specific to each distro so I didn't add a dkms.conf yet. I'll throw together a PKGBUILD for Arch tomorrow.

**Comment by zamlz** [comment]
Thanks @HannesMann and appreciate the update too, I'll try it out and let you know if I run into any issues
