### ISSUE TITLE
Unable to make - Linux headers issue

### ISSUE THREAD

**Issue by Ladztho** [hannesmann/gcadapter-oc-kmod#11]
![Screenshot from 2022-10-15 14-52-03](https://user-images.githubusercontent.com/84239500/195990157-f954b660-70c6-4aac-b503-68b9ee064546.png)
I'm having an issue with the make file. I'm on Ubuntu 20.04 but the same issue applies on 22.04.

Apologies for any incompetency too: this is my first issue post.

Thanks in advance!

**Comment by hannesmann** [comment]
Tried installing `flex` (with `sudo apt install flex`)? I'm not sure why it's needed, that's not a package required by the module itself, but maybe the Linux kernel needs it for building modules.

**Comment by Ladztho** [comment]
![Screenshot from 2022-10-16 13-03-33](https://user-images.githubusercontent.com/84239500/196034373-5c791f6e-3d11-45e7-a0ef-c4f4c6ef2b83.png)
Installed `flex` and `bison` and now I'm getting this error

I appreciate the response/help

**Comment by hannesmann** [comment]
Try running `make` without `sudo`.

**Comment by hannesmann** [comment]
Now that's interesting... If you haven't rebooted in a while I would try that first (running kernel doesn't match the installed one) but if that doesn't work something else is wrong with your system.

**Comment by Ladztho** [comment]
![Screenshot from 2022-10-16 13-27-54](https://user-images.githubusercontent.com/84239500/196035417-b76355a7-84ea-4a80-b646-ca1599636c9e.png)
Rebooted and the same thing. I could install a different distro or reinstall tomorrow at work and see if that makes a difference? I don't have a USB drive handy till then.

**Comment by hannesmann** [comment]
Sure, I have no idea what might be causing that error for a module you built yourself so if you find a solution let me know.

**Comment by Ladztho** [comment]
Apologies for the delay on this. I installed EndeavourOS and the module ran without any issues. So I presume it was some borked kernel from an old Ubuntu install or something.

Appreciate the help!

**Comment by itsonlyMiRE** [comment]
not sure if this applies to your situation as well, or if you still need it, but i've run into this problem before after upgrading linux headers (and had to do it again now after getting the error again). i see in your initial post you tried `sudo apt install linux-headers-$(uname -r)` but running `sudo apt install --reinstall linux-headers-$(uname -r)` to reinstall them, and then reboot, allowed me to run the make without errors.

**Comment by Ladztho** [comment]
> 

I can't remember if I just manually uninstalled it at some point and tried that. I think I may have.

Although it's much appreciated I'm sure for others who will need it. Thanks!
