### ISSUE TITLE
(Steam Deck) bash: make: command not found

### ISSUE THREAD

**Issue by Nannose** [hannesmann/gcadapter-oc-kmod#15]
![Screenshot_20221228_124032](https://user-images.githubusercontent.com/16147700/209852181-8e3b618e-c566-47fe-b25e-7e92f81a926e.png)
I don't know what happened, I guess a SteamOS update removed `make` or something since I wiped my Deck when it was working before, but now it's giving this new error even after installing the neptune headers and I don't know how to resolve it.

**Comment by JoeBudson** [comment]
I also have this issue.

**Comment by hannesmann** [comment]
Valve must have removed Make from the default SteamOS installation. 

Does `sudo pacman -S base-devel linux-neptune-headers` work? This should install everything needed, even if Valve decides to tweak the default installation in the future.

**Comment by Nannose** [comment]
> Valve must have removed Make from the default SteamOS installation.
> 
> Does `sudo pacman -S base-devel linux-neptune-headers` work? This should install everything needed, even if Valve decides to tweak the default installation in the future.

Will that just overwrite stuff if I've already installed the neptune headers? Do I need to run 
`sudo pacman-key --init` 
`sudo pacman-key --populate archlinux`
again first?

**Comment by hannesmann** [comment]
> Will that just overwrite stuff if I've already installed the neptune headers?

Yes, it should tell you "package is up to date -- reinstalling".

> Do I need to run
> sudo pacman-key --init
> sudo pacman-key --populate archlinux
> again first?

As far as I know you only need to run that once after every SteamOS update.

**Comment by Nannose** [comment]
> Valve must have removed Make from the default SteamOS installation.
> 
> Does `sudo pacman -S base-devel linux-neptune-headers` work? This should install everything needed, even if Valve decides to tweak the default installation in the future.

This did in fact work, I was able to use `make` and load the module properly. It prompted me in the terminal asking which packages to install and I just hit enter to default to all of them, do you actually need everything in that group for `make` to work?

**Comment by hannesmann** [comment]
> do you actually need everything in that group for make to work

Probably not, but I don't know which packages Valve have installed by default so the easiest way is to install the whole group. You're going to need `gcc` anyway which takes up most of the disk space (~170 MB).

Issue has been fixed by commit: d537442c5ca5dc02ecbd35791e56e9509653c1f5
