### ISSUE TITLE
fails to overclock on Arch

### ISSUE THREAD

**Issue by KaleandStrawberry** [hannesmann/gcadapter-oc-kmod#16]
I've tried both the pkgbuild and installing manually through insmod but slippi still reports a 500hz polling rate.

dmesg output:
`[  682.231679] hid-generic 0003:057E:0337.0005: hiddev96,hidraw1: USB HID v1.10 Device [Nintendo WUP-028] on usb-0000:02:00.0-4/input0
[  682.231708] gcadapter_oc: Adapter connected
[  682.231709] gcadapter_oc: bInterval value of endpoint 0x81 set to 1.
[  682.231710] gcadapter_oc: bInterval value of endpoint 0x02 set to 1.
[  683.253357] gcadapter_oc: Warning! Failed to acquire lock for USB device (error: -16). Resetting device anyway...
`

**Comment by hannesmann** [comment]
Is the rate lowered to 250 Hz if you run `insmod gcadapter_oc.ko rate=4`? Not all adapters can do 1000 Hz, my official Nintendo adapter maxes out at 800-900 Hz.

**Comment by KaleandStrawberry** [comment]
weird, it does, I have gotten this same adapter to overclock to 1000 before with this kernel mod before and even on the same computer under a different OS. I tried another adapter I have lying around and it works flawlessly now, thank you.
