### ISSUE TITLE
No longer working on Steam Deck

### ISSUE THREAD

**Issue by Nannose** [hannesmann/gcadapter-oc-kmod#21]
After an OS update I went through the steps to install everything again and it no longer works. When I try to install the neptune headers I get this error:
![Screenshot_20231022_210852](https://github.com/hannesmann/gcadapter-oc-kmod/assets/16147700/c855a5a7-8e7a-4dee-bb9f-c5f62a1ae810)
Then if I try to run:
`make`
In the proper directory it says the command isn't found.

**Comment by Nannose** [comment]
Okay I figured it out, I just deleted /etc/ld.so.conf.d/fakeroot.conf with `sudo rm -rf` and then tried redownloading the headers and developer tools and it worked this time.

No idea why that was causing a problem but it turns out the simplest solution was the right one.

**Comment by hannesmann** [comment]
Thanks for the report, this is probably solved by the updated SteamOS instructions. If not you can add `--overwrite '*'` after the `sudo pacman -S` command.
