### ISSUE TITLE
Updated Steam Deck instructions

### ISSUE THREAD

**Issue by linuxgamingcentral** [hannesmann/gcadapter-oc-kmod#23]
Now that SteamOS 3.5 is here, the instructions for compiling the program on Steam Deck are outdated. Instructions should now be as follows:
```
sudo steamos-readonly disable
sudo pacman-key --init
sudo pacman-key --populate archlinux holo
sudo pacman -S --needed base-devel linux-neptune-61-headers

git clone https://github.com/hannesmann/gcadapter-oc-kmod.git
cd gcadapter-oc-kmod
make
sudo insmod gcadapter_oc.ko
```
Can confirm by running these commands I got the adapter overclocked on SteamOS 3.5.7 stable.

**Comment by hannesmann** [comment]
Updated, thanks! 

Side note: Now that the kernel package name depends on the version, could you try this and see if it works to "autodetect" the package name?

```
sudo pacman -S --needed base-devel "$(cat /usr/lib/modules/$(uname -r)/pkgbase)-headers"
```

**Comment by linuxgamingcentral** [comment]
Seems to pick up the package name just fine:
```
(deck@steamdeck gcadapter-oc-kmod)$ sudo pacman -S --needed base-devel "$(cat /usr/lib/modules/$(uname -r)/pkgbase)-headers"
warning: base-devel-1-1 is up to date -- skipping
warning: linux-neptune-61-headers-6.1.52.valve9-1 is up to date -- skipping
 there is nothing to do
```
Now I'm just wondering if there's a way to keep the overclock persistent across reboots.

**Comment by hannesmann** [comment]
> Seems to pick up the package name just fine

Good to know, that should make the instructions more future proof when Valve updates the kernel again. 

> Now I'm just wondering if there's a way to keep the overclock persistent across reboots.

You can try installing the module and adding an entry into /etc/modules-load.d (this is similar to what the Arch Linux package does):
```
sudo make modules_install
echo "gcadapter_oc" | sudo tee /etc/modules-load.d/gcadapter_oc
```

Or, you could just try the DKMS package from the AUR: https://aur.archlinux.org/packages/gcadapter-oc-dkms

**Comment by linuxgamingcentral** [comment]
Running `sudo make modules_install` results in:
`make: *** No rule to make target 'modules_install'.  Stop.`

**Comment by hannesmann** [comment]
Try copying manually:
```
sudo mkdir -p "/usr/lib/modules/$(uname -r)/extra"
sudo cp gcadapter_oc.ko "/usr/lib/modules/$(uname -r)/extra"
sudo depmod
```

**Comment by hannesmann** [comment]
Sorry, the file in modules-load.d should be called gcadapter_oc.conf, not gcadapter_oc. 

Try this:
```
echo "gcadapter_oc" | sudo tee /etc/modules-load.d/gcadapter_oc.conf
```

If it still doesn't work I'm afraid I don't know of any solutions. I don't own a Steam Deck so I can't test it myself.

**Comment by linuxgamingcentral** [comment]
Success!! Thanks! I made a [guide](https://linuxgamingcentral.com/posts/overclock-gc-adapter-on-steam-deck/) to go along with this. So I guess we're good to go now.

**Comment by linuxgamingcentral** [comment]
Can you add this link to the README please? https://github.com/linuxgamingcentral/gcadapter-oc-kmod-deck

**Comment by hannesmann** [comment]
> Can you add this link to the README please? https://github.com/linuxgamingcentral/gcadapter-oc-kmod-deck

Neat, added! I'll keep the manual instructions in the repo for those that want to set it up manually but this is definitely an easier option. I think this issue can be closed now.
