### ISSUE TITLE
Never coded before, does this work on Windows?

### ISSUE THREAD

**Issue by condefombrilac** [HannesMann/gcadapter-oc-kmod#3]
Hello!

I just bought a new Lenovo laptop, and to my dismay I can't seem to make the HIDUSBF overclocking method to work... I followed all the instructions.

I found your work browsing on the web, and I am willing to attemp making it work, but I have never coded before... does this work on Windows 10? What program should I use to type in the commands? does it have to done everytime I wish to overclock the adapter?

Thanks in advance!

**Comment by HannesMann** [comment]
This is a kernel module for Linux so you're not gonna be able to run it on Windows, unfortunately. HIDUSBF seems to be your best bet for getting it to work on Windows.

(I actually tried porting to Windows back in 2017 but Microsoft locks down the Windows kernel so you can't make the same modifications as the module makes on Linux, I'm not sure how HIDUSBF manages to overclock the adapter)
