### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by real-F-00** [HannesMann/gcadapter-oc-kmod#5]
on linux mint 20.1 this is what using the "make" command does:
`make -C /lib/modules/5.4.0-58-generic/build M=/home/f-00/Documents/polling fix/gcadapter-oc-kmod-master modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-58-generic'
make[1]: *** No rule to make target 'fix/gcadapter-oc-kmod-master'.  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-58-generic'
make: *** [Makefile:6: all] Error 2`

the terminal simply says that, no idea on how to fix, but from what i read from that the files are like in the wrong directory or something.

**Comment by real-F-00** [comment]
i figured i had to install the linux headers generic, my fault

**Comment by HannesMann** [comment]
Actually I know what the issue is, I forgot to escape the source directory in the Makefile :slightly_smiling_face:. Give me a minute and I'll fix it.

**Comment by HannesMann** [comment]
Try running `git pull` and see if it works now.
