### ISSUE TITLE
make clean deletes gcadapter_oc.ko

### ISSUE THREAD

**Issue by RaghavRao** [HannesMann/gcadapter-oc-kmod#9]
The instructions state to `make`, then `make clean` then `sudo insmod` however insmod fails because make clean has deleted the .ko file

The video however avoids this step.

This may confuse new users.

**Comment by HannesMann** [comment]
They're not steps to be done in order, but I updated the instructions to make it clearer. 90961037c371da2ec707dba60217a87ca817965c
